# Generated by Django 4.2.6 on 2023-10-26 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="images",
            new_name="image",
        ),
    ]
